#PBS -N Norm_1_0.1
#PBS -l select=1:ncpus=4:ngpus=2:mem=8gb:gpu_model=p100,walltime=24:00:00

cd /home/$USER/StrIde
source activate tensorflow

python scripts/run_net.py --dataset /scratch3/rdefeve/nn-sid/training/lj-r2.0_samples.npy \
						  --labels /scratch3/rdefeve/nn-sid/training/lj-r2.0_labels.npy \
						  --net pc \
						  --weights /scratch3/ctargon/weights/gauss_mu_1_sig_0.1_$NUM

python scripts/run_inference.py --dataset /scratch3/rdefeve/nn-sid/training/lj-r2.0_test_samples.npy \
								--labels /scratch3/rdefeve/nn-sid/training/lj-r2.0_test_labels.npy \
								--weights /scratch3/ctargon/weights/gauss_mu_1_sig_0.1_$NUM

